## Append samples of your project ##
resources:
- infrastructure_v1beta1_nvidiacarbidecluster.yaml
- infrastructure_v1beta1_nvidiacarbidemachine.yaml
- infrastructure_v1beta1_nvidiacarbidemachinetemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
