## Append samples of your project ##
resources:
- infrastructure_v1beta1_ncxinfracluster.yaml
- infrastructure_v1beta1_ncxinframachine.yaml
- infrastructure_v1beta1_ncxinframachinetemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
